swagger: '2.0'
info:
  version: 0.0.1
  title: Master Patient Index
host: 'localhost:3000'
basePath: /mpi
schemes:
  - http
paths:
  /Patient:
    get:
      description: >-
        Fetches a bundle of all Patient resources for the specified patient or
        search criteria.
      operationId: 'GET /Patient?[searchParameters]'
      produces:
        - application/json+fhir
      parameters:
        - in: header
          name: authorization
          description: Session token
          required: true
          type: string
          format: uuid
        - in: query
          name: name
          description: A portion of either family or given name of the patient
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Bundle'
        '403':
          description: forbidden
        '404':
          description: resource not found
    post:
      description: Creates a single patient
      operationId: POST /Patient
      produces:
        - application/json+fhir
      parameters:
        - in: header
          name: authorization
          description: Session token
          required: true
          type: string
          format: uuid
        - in: header
          name: Content-Type
          description: Content format
          required: true
          type: string
          default: application/json+fhir
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Bundle'
      responses:
        '201':
          description: created
          schema:
            $ref: '#/definitions/OperationOutcome'
        '400':
          description: bad request
        '403':
          description: forbidden
  '/Patient/{id}':
    get:
      description: Return a single Patient for the specified id
      operationId: 'GET /Patient/{id}'
      produces:
        - application/json+fhir
      parameters:
        - in: path
          name: id
          description: The patient's identifier
          required: true
          type: string
        - in: header
          name: authorization
          description: Session token
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Patient'
        '403':
          description: forbidden
        '404':
          description: resource not found
definitions:
  Bundle:
    properties:
      resourceType:
        type: string
        example: Bundle
      entry:
        type: array
        items:
          $ref: '#/definitions/Entry'
  Entry:
    properties:
      resource:
        $ref: '#/definitions/Patient'
  Patient:
    properties:
      resourceType:
        type: string
        example: Patient
      id:
        type: string
        example: 1c2fc0f9-3ba0-42ae-9424-82dc2d78be7b
      identifier:
        type: array
        items:
          $ref: '#/definitions/Identifier'
      name:
        $ref: '#/definitions/HumanName'
      telecom:
        type: string
        example: 07700 900000
      gender:
        type: string
        enum:
          - male
          - female
          - other
          - unknown
      deceasedBoolean:
        type: boolean
        example: 'false'
      birthDate:
        type: string
        example: 22-Jun-1938
      address:
        $ref: '#/definitions/Address'
  Identifier:
    properties:
      system:
        type: string
        example: 'urn:oid:2.16.840.1.113883.2.1.3.2.4.16.53'
      value:
        type: string
        example: '2206383919'
  HumanName:
    properties:
      resourceType:
        type: string
        example: HumanName
      family:
        type: string
        example: Keddie
      given:
        type: array
        items:
          type: string
          example: Aengue
      prefix:
        type: string
        example: Mr
  Address:
    properties:
      resourceType:
        type: string
        example: Address
      line:
        type: array
        items:
          type: string
          example: '26, High Street'
      city:
        type: string
        example: Dundee
      district:
        type: string
        example: Tayside
      postalCode:
        type: string
        example: DU2 3SK
      country:
        type: string
        example: United Kingdom
  OperationOutcome:
    properties:
      resourceType:
        type: string
        example: OperationOutcome
      issue:
        type: array
        items:
          $ref: '#/definitions/Issue'
  Issue:
    properties:
      severity:
        type: string
        example: information
      code:
        type: string
        example: informational
      diagnostics:
        type: string
        example: Successfully created resource(s)
